//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicTheater.Web.Views.Theater.Controls
{


    public partial class MediaManagerEditPanel
    {

        /// <summary>
        /// lvMediaManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lvMediaManager;

        protected global::System.Web.UI.WebControls.HyperLink btnMassUploader;

        protected global::System.Web.UI.WebControls.HyperLink btnToMediaManager;

        protected global::System.Web.UI.WebControls.Button btnSubmitAfterReorder;

        protected global::System.Web.UI.WebControls.Button btnSaveNow;

        protected global::System.Web.UI.WebControls.DataPager MediaManagerDataPager;
    }
}
